In [2]:
import pandas as pd
import sqlite3
with sqlite3.connect('data/chinook.db') as con:
    df_cus=pd.read_sql("Select * from customers", con=con
    )
with sqlite3.connect('data/chinook.db') as con:
    df_inv=pd.read_sql("Select * from invoices", con=con
    )
df_new_sql=pd.merge(df_inv, df_cus, how='inner', on='CustomerId')
df_sql_grouped=df_new_sql.groupby('CustomerId')
df_sql_grouped.count()

,InvoiceId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
CustomerId,,,,,,,,,,,,,,,,,,,,
1,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
2,7,7,7,7,0,7,7,7,7,7,0,7,7,0,7,7,7,0,7,7
3,7,7,7,7,7,7,7,7,7,7,0,7,7,7,7,7,7,0,7,7
4,7,7,7,7,0,7,7,7,7,7,0,7,7,0,7,7,7,0,7,7
5,7,7,7,7,0,7,7,7,7,7,7,7,7,0,7,7,7,7,7,7
6,7,7,7,7,0,7,7,7,7,7,0,7,7,0,7,7,7,0,7,7
7,7,7,7,7,0,7,7,7,7,7,0,7,7,0,7,7,7,0,7,7
8,7,7,7,7,0,7,7,7,7,7,0,7,7,0,7,7,7,0,7,7
9,7,7,7,7,0,7,7,7,7,7,0,7,7,0,7,7,7,0,7,7
10,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
11,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
12,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
13,7,7,7,7,7,7,7,7,7,7,0,7,7,7,7,7,7,7,7,7
14,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
15,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
16,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
17,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
18,7,7,7,7,7,7,7,7,7,7,0,7,7,7,7,7,7,7,7,7
19,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
20,7,7,7,7,7,7,7,7,7,7,0,7,7,7,7,7,7,0,7,7
21,7,7,7,7,7,7,7,7,7,7,0,7,7,7,7,7,7,0,7,7
22,7,7,7,7,7,7,7,7,7,7,0,7,7,7,7,7,7,0,7,7
23,7,7,7,7,7,7,7,7,7,7,0,7,7,7,7,7,7,0,7,7
24,7,7,7,7,7,7,7,7,7,7,0,7,7,7,7,7,7,0,7,7
25,7,7,7,7,7,7,7,7,7,7,0,7,7,7,7,7,7,0,7,7
26,7,7,7,7,7,7,7,7,7,7,0,7,7,7,7,7,7,0,7,7
27,7,7,7,7,7,7,7,7,7,7,0,7,7,7,7,7,7,0,7,7
28,7,7,7,7,7,7,7,7,7,7,0,7,7,7,7,7,7,0,7,7
29,7,7,7,7,7,7,7,7,7,7,0,7,7,7,7,7,7,0,7,7
30,7,7,7,7,7,7,7,7,7,7,0,7,7,7,7,7,7,0,7,7
31,7,7,7,7,7,7,7,7,7,7,0,7,7,7,7,7,7,0,7,7
32,7,7,7,7,7,7,7,7,7,7,0,7,7,7,7,7,7,0,7,7
33,7,7,7,7,7,7,7,7,7,7,0,7,7,7,7,7,7,0,7,7
34,7,7,7,7,0,7,0,7,7,7,0,7,7,0,7,0,7,0,7,7
35,7,7,7,7,0,7,0,7,7,7,0,7,7,0,7,0,7,0,7,7
36,7,7,7,7,0,7,7,7,7,7,0,7,7,0,7,7,7,0,7,7
37,7,7,7,7,0,7,7,7,7,7,0,7,7,0,7,7,7,0,7,7
38,7,7,7,7,0,7,7,7,7,7,0,7,7,0,7,7,7,0,7,7
39,7,7,7,7,0,7,7,7,7,7,0,7,7,0,7,7,7,0,7,7
40,7,7,7,7,0,7,7,7,7,7,0,7,7,0,7,7,7,0,7,7
41,7,7,7,7,0,7,7,7,7,7,0,7,7,0,7,7,7,0,7,7
42,7,7,7,7,0,7,7,7,7,7,0,7,7,0,7,7,7,0,7,7
43,7,7,7,7,0,7,7,7,7,7,0,7,7,0,7,7,7,0,7,7
44,7,7,7,7,0,7,7,7,7,7,0,7,7,0,7,7,7,0,7,7
45,7,7,7,7,0,7,7,7,7,7,0,7,7,0,7,7,0,0,7,7
46,7,7,7,7,7,7,0,7,7,7,0,7,7,7,7,0,7,0,7,7
47,7,7,7,7,7,7,7,7,7,7,0,7,7,7,7,7,7,0,7,7
48,7,7,7,7,7,7,7,7,7,7,0,7,7,7,7,7,7,0,7,7
49,7,7,7,7,0,7,7,7,7,7,0,7,7,0,7,7,7,0,7,7
50,7,7,7,7,0,7,7,7,7,7,0,7,7,0,7,7,7,0,7,7
51,7,7,7,7,0,7,7,7,7,7,0,7,7,0,7,7,7,0,7,7
52,7,7,7,7,0,7,7,7,7,7,0,7,7,0,7,7,7,0,7,7
53,7,7,7,7,0,7,7,7,7,7,0,7,7,0,7,7,7,0,7,7
54,7,7,7,7,0,7,7,7,7,7,0,7,7,0,7,7,7,0,7,7
55,7,7,7,7,7,7,7,7,7,7,0,7,7,7,7,7,7,0,7,7
56,7,7,7,7,0,7,7,7,7,7,0,7,7,0,7,7,7,0,7,7
57,7,7,7,7,0,7,0,7,7,7,0,7,7,0,7,0,7,0,7,7
58,7,7,7,7,0,7,7,7,7,7,0,7,7,0,7,7,7,0,7,7
59,6,6,6,6,0,6,6,6,6,6,0,6,6,0,6,6,6,0,6,6

In [3]:
df_mov=pd.read_csv('data/movie.csv')
df_mov1=df_mov[['director_name', 'color']]
df_mov2=df_mov[['director_name', 'num_critic_for_reviews']]
df_movn=df_mov1.merge(df_mov2, 'left', 'director_name' )
df_movn1=df_mov1.merge(df_mov2, 'outer', 'director_name')
print(df_movn.count('columns'))
print(df_movn1.count('columns'))

0        3
1        3
2        3
3        3
4        3
        ..
30295    3
30296    3
30297    3
30298    3
30299    3
Length: 30300, dtype: int64
0        3
1        3
2        3
3        3
4        3
        ..
30295    2
30296    2
30297    2
30298    2
30299    2
Length: 30300, dtype: int64

In [4]:
df_tit=pd.read_excel('data/titanic.xlsx')
df_tit_gr=df_tit.groupby('Pclass')
print(df_tit_gr.Age.agg('mean'))
print(df_tit_gr.Fare.agg('sum'))
print(df_tit_gr.PassengerId.count())

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64
Pclass
1    18177.4125
2     3801.8417
3     6714.6951
Name: Fare, dtype: float64
Pclass
1    216
2    184
3    491
Name: PassengerId, dtype: int64

In [5]:
print(df_mov.groupby(['color', 'director_name'])['num_critic_for_reviews'].sum())
print(df_mov.groupby(['color', 'director_name'])['duration'].mean())

color            director_name
Black and White  Akira Kurosawa        153.0
                 Aleksey German        121.0
                 Alex Garland          489.0
                 Alexander Payne       433.0
                 Alfred Hitchcock      434.0
                                       ...
Color            Zoran Lisinac          17.0
                 Álex de la Iglesia     71.0
                 Émile Gaudreault       67.0
                 Éric Tessier            9.0
                 Étienne Faure           9.0
Name: num_critic_for_reviews, Length: 2490, dtype: float64
color            director_name
Black and White  Akira Kurosawa        202.0
                 Aleksey German        177.0
                 Alex Garland          108.0
                 Alexander Payne       115.0
                 Alfred Hitchcock      119.0
                                       ...
Color            Zoran Lisinac         108.0
                 Álex de la Iglesia    104.0
                 Émile Gaudreault       92.0
                 Éric Tessier           99.0
                 Étienne Faure          98.0
Name: duration, Length: 2490, dtype: float64

In [6]:
df_flight=pd.read_parquet('data/flights')

In [7]:
df_flight.head()

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,Tail_Number,...,Div4WheelsOff,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum
0,2022,2,4,15,5,2022-04-15,OH,20397,OH,N582NN,...,None,None,None,None,None,None,None,None,None,None
1,2022,2,4,16,6,2022-04-16,OH,20397,OH,N575NN,...,None,None,None,None,None,None,None,None,None,None
2,2022,2,4,17,7,2022-04-17,OH,20397,OH,N562NN,...,None,None,None,None,None,None,None,None,None,None
3,2022,2,4,18,1,2022-04-18,OH,20397,OH,N548NN,...,None,None,None,None,None,None,None,None,None,None
4,2022,2,4,19,2,2022-04-19,OH,20397,OH,N597NN,...,None,None,None,None,None,None,None,None,None,None

In [8]:
df_flight['counter']=1
df_flight_gr=df_flight[['Year', 'Month', 'ArrDelay', 'DepDelay', 'counter']].groupby(['Year', 'Month'])
print(df_flight_gr.count()['counter'])
print(df_flight_gr.mean('ArrDelay'))
print(df_flight_gr.max('DepDelay'))

Year  Month
2022  1        537902
      10       572287
      11       546410
      12       557095
      2        495713
      3        564853
      4        556502
      5        578819
      6        577283
      7        594957
      8        589810
      9        557494
Name: counter, dtype: int64
            counter
Year Month
2022 1          1.0
     10         1.0
     11         1.0
     12         1.0
     2          1.0
     3          1.0
     4          1.0
     5          1.0
     6          1.0
     7          1.0
     8          1.0
     9          1.0
            counter
Year Month
2022 1            1
     10           1
     11           1
     12           1
     2            1
     3            1
     4            1
     5            1
     6            1
     7            1
     8            1
     9            1

In [9]:
def isChild(Age):
    if Age>18:
        return 'Adult'
    else:
        return'Child'
df_tit['Age_Group']=df_tit['Age'].apply(isChild)

In [10]:
with sqlite3.connect('data/chinook.db') as con:
    df_sql_emp=pd.read_sql("Select * from employees", con=con)

In [11]:
df_sql_emp_gr=df_sql_emp.groupby('Title')
import numpy as np

In [12]:
def norm(salary):
    return (salary-np.min(salary))/(np.max(salary)-np.min(salary))

In [13]:
df_sql_emp_gr['ReportsTo'].apply(norm)

Title
General Manager      0   NaN
IT Manager           5   NaN
IT Staff             6   NaN
                     7   NaN
Sales Manager        1   NaN
Sales Support Agent  2   NaN
                     3   NaN
                     4   NaN
Name: ReportsTo, dtype: float64

In [14]:
def mov_func(duration):
    if duration<60:
        return 'short'
    elif duration<120:
        return 'medium'
    else:
        return 'long'
print(df_mov['duration'].apply(mov_func))

0         long
1         long
2         long
3         long
4         long
         ...
4911    medium
4912     short
4913    medium
4914    medium
4915    medium
Name: duration, Length: 4916, dtype: object

In [15]:
df_tit

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_Group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Adult
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Adult
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Child
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Adult
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Adult

In [16]:
def tit_pipe(df):
    df.loc[df['Survived']==1]
    df.Age.fillna(df.Age.mean)
    df['Fare_Per_Age']=df.Fare/df.Age
df_tit.pipe(tit_pipe)

In [17]:
df_flight

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,Tail_Number,...,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum,counter
0,2022,2,4,15,5,2022-04-15,OH,20397,OH,N582NN,...,None,None,None,None,None,None,None,None,None,1
1,2022,2,4,16,6,2022-04-16,OH,20397,OH,N575NN,...,None,None,None,None,None,None,None,None,None,1
2,2022,2,4,17,7,2022-04-17,OH,20397,OH,N562NN,...,None,None,None,None,None,None,None,None,None,1
3,2022,2,4,18,1,2022-04-18,OH,20397,OH,N548NN,...,None,None,None,None,None,None,None,None,None,1
4,2022,2,4,19,2,2022-04-19,OH,20397,OH,N597NN,...,None,None,None,None,None,None,None,None,None,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6729120,2022,3,7,12,2,2022-07-12,DL,19790,DL,N712TW,...,None,None,None,None,None,None,None,None,None,1
6729121,2022,3,7,13,3,2022-07-13,DL,19790,DL,N703TW,...,None,None,None,None,None,None,None,None,None,1
6729122,2022,3,7,14,4,2022-07-14,DL,19790,DL,N722TW,...,None,None,None,None,None,None,None,None,None,1
6729123,2022,3,7,15,5,2022-07-15,DL,19790,DL,N718TW,...,None,None,None,None,None,None,None,None,None,1
6729124,2022,3,7,16,6,2022-07-16,DL,19790,DL,N703TW,...,None,None,None,None,None,None,None,None,None,1

In [18]:
def pipe_flight(df):
    df['DepDelay']=pd.to_numeric(df['DepDelay'])
    df.loc[df['DepDelay']>30].shape
    df['AirTime']=pd.to_numeric(df['AirTime'])
    df['Delay_Per_Hour']=df['DepDelay']/df["AirTime"]

In [19]:
piped_df_flight=df_flight.pipe(pipe_flight)

0         -0.135135
1         -0.042254
2         -0.169014
3         -0.106667
4         -0.097222
             ...
6729120    0.030534
6729121    0.143939
6729122    0.028986
6729123    0.126866
6729124   -0.045802
Name: Delay_Per_Hour, Length: 6729125, dtype: float64